language: ruby
rvm:
  - 2.1.4
cache: bundler
bundler_args: --without development production
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:setup RAILS_ENV=test
  - bundle exec rake db:migrate RAILS_ENV=test
