apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sensus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: sensus
    spec:
      containers:
      - name: sensus
        image: eu.gcr.io/sensus-154219/sensus:latest
        ports:
        - containerPort: 2300
        env:
        - name: HANAMI_ENV
          value: production
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database
              key: url
        - name: WEB_SESSIONS_SECRET
          valueFrom:
            secretKeyRef:
              name: session
              key: secret
