version: '2'
services:
  sensus:
    build: .
    image: 'eu.gcr.io/sensus-154219/sensus:latest'
    links:
      - postgres
    volumes:
      - .:/var/sensus
    ports:
      - '2300:2300'
  postgres:
    image: 'postgres:9.6.1'
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/init-sensus-db.sh
  test:
    image: 'eu.gcr.io/sensus-154219/sensus:latest'
    links:
      - postgres
    volumes:
      - .:/var/sensus
    ports:
      - '2300:2300'
    command: 'bundle exec rake'
